main:main.o Queue_1.o BiTree_1.o Stack_1.o Graph_1.o
	gcc  main.o Queue_1.o BiTree_1.o Stack_1.o Graph_1.o -o a.out

main.o:main.c
	gcc  -c main.c

Queue_1.o:Queue_1.c
	gcc  -c Queue_1.c

BiTree_1.o:BiTree_1.c
	gcc  -c BiTree_1.c

Stack_1.o:Stack_1.c
	gcc  -c Stack_1.c

Graph_1.o:Graph_1.c
	gcc  -c Graph_1.c

clean:
	rm main.o && rm Queue_1.o && rm BiTree_1.o && rm Stack_1.o && rm Graph_1.o && rm a.out


